src/Entity/Personnels.php
<?php

namespace App\Entity;

use App\Repository\PersonnelsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=PersonnelsRepository::class)
 * @UniqueEntity(fields="matricule_pers", message="Le matricule entré est déjà existant")
 */
class Personnels
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", length=6, unique=true)
     */
    private $matricule_pers;

    /**
     * @ORM\Column(type="string", length=24)
     */
    private $grade_pers;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $nom_pers;

    /**
     * @ORM\Column(type="string", length=128, nullable=true)
     */
    private $prenoms_pers;

    /**
     * @ORM\Column(type="string", length=128)
     */
    private $fonctions_pers;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_out_cr;

    /**
     * @ORM\Column(type="datetime")
     */
    private $pers_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $pers_updated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="personnels")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Absences::class, mappedBy="personnels")
     */
    private $absences;

    /**
     * @ORM\OneToMany(targetEntity=Designations::class, mappedBy="personnels")
     */
    private $designations;
    /**
     * @ORM\ManyToOne(targetEntity=Unites::class, inversedBy="personnels")
     */
    private $unites;
    public function __construct()
    {
        $this->absences = new ArrayCollection();
        $this->designations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMatriculePers(): ?int
    {
        return $this->matricule_pers;
    }

    public function setMatriculePers(int $matricule_pers): self
    {
        $this->matricule_pers = $matricule_pers;

        return $this;
    }

    public function getGradePers(): ?string
    {
        return $this->grade_pers;
    }

    public function setGradePers(string $grade_pers): self
    {
        $this->grade_pers = $grade_pers;

        return $this;
    }

    public function getNomPers(): ?string
    {
        return $this->nom_pers;
    }

    public function setNomPers(string $nom_pers): self
    {
        $this->nom_pers = $nom_pers;

        return $this;
    }

    public function getPrenomsPers(): ?string
    {
        return $this->prenoms_pers;
    }

    public function setPrenomsPers(?string $prenoms_pers): self
    {
        $this->prenoms_pers = $prenoms_pers;

        return $this;
    }

    public function getFonctionsPers(): ?string
    {
        return $this->fonctions_pers;
    }

    public function setFonctionsPers(string $fonctions_pers): self
    {
        $this->fonctions_pers = $fonctions_pers;

        return $this;
    }

    public function isIsOutCr(): ?bool
    {
        return $this->is_out_cr;
    }

    public function setIsOutCr(?bool $is_out_cr): self
    {
        $this->is_out_cr = $is_out_cr;

        return $this;
    }

    public function getPersCreated(): ?\DateTimeInterface
    {
        return $this->pers_created;
    }

    public function setPersCreated(\DateTimeInterface $pers_created): self
    {
        $this->pers_created = $pers_created;

        return $this;
    }

    public function getPersUpdated(): ?\DateTimeInterface
    {
        return $this->pers_updated;
    }

    public function setPersUpdated(?\DateTimeInterface $pers_updated): self
    {
        $this->pers_updated = $pers_updated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }
    public function getUnites(): ?Unites
    {
        return $this->unites;
    }

    public function setUnites(?Unites $unites): self
    {
        $this->unites = $unites;

        return $this;
    }
    /**
     * @return Collection<int, Absences>
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(Absences $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setPersonnels($this);
        }

        return $this;
    }

    public function removeAbsence(Absences $absence): self
    {
        if ($this->absences->removeElement($absence)) {
            // set the owning side to null (unless already changed)
            if ($absence->getPersonnels() === $this) {
                $absence->setPersonnels(null);
            }
        }

        return $this;
    }

    public function getInZoneDeListe(): ?string {
       // if($this.getMatriculePers()==1)
          //  return $this->getGradePers() . ' ' . $this->getNomPers() . ' ' . $this->getPrenomsPers() . ' (PO) ' ;
       // else    
            return $this->getGradePers() . ' ' . $this->getNomPers() . ' ' . $this->getPrenomsPers() . ' (Mle ' . $this->getMatriculePers() . ')' ;

    }

    /**
     * @return Collection<int, Designations>
     */
    public function getDesignations(): Collection
    {
        return $this->designations;
    }

    public function addDesignation(Designations $designation): self
    {
        if (!$this->designations->contains($designation)) {
            $this->designations[] = $designation;
            $designation->setPersonnels($this);
        }

        return $this;
    }

    public function removeDesignation(Designations $designation): self
    {
        if ($this->designations->removeElement($designation)) {
            // set the owning side to null (unless already changed)
            if ($designation->getPersonnels() === $this) {
                $designation->setPersonnels(null);
            }
        }

        return $this;
    }
}

src/Form/PersonnelsType.php
<?php

namespace App\Form;

use App\Entity\Personnels;
use App\Entity\Unites;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class PersonnelsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('matricule_pers', NumberType::class, [
                'label' => 'Matricule',
                'required' => true,
                'invalid_message' => 'Veuillez entrer caractère numerique.',
            ])
            ->add('grade_pers', ChoiceType::class, [
                'choices' => [
                    'GCA'   => 'GCA',   'GDI'   => 'GDI',
                    'GBR'   => 'GBR',   'COL'   => 'COL',
                    'LCOL'  => 'LCOL',  'CEN'   => 'CEN',
                    'CNE'   => 'CNE',   'LTN'   => 'LTN',
                    'SLT'   => 'SLT',   'GPCE'  => 'GPCE',
                    'GPHC'  => 'GPHC',  'GP1C'  => 'GP1C',
                    'GP2C'  => 'GP2C',  'GHC'   => 'GHC',
                    'G1C'   => 'G1C',   'G2C'   => 'G2C',
                    'GST'   => 'GST',   'EG'    => 'EG',
                ],
                'label' => 'Grade',
                'expanded' => false,
                'attr'  => [
                    'class' => 'form-group form-control select2 select2-hidden-accessible',
                ]
            ])
            ->add('nom_pers', TextType::class, [
                'label' => 'Nom',
                'required' => true,
            ])
            ->add('prenoms_pers', TextType::class, [
                'label' => 'Prénoms',
            ])
            ->add('fonctions_pers', TextType::class, [
                'label' => 'Fonction',
                'required' => true,
            ])
            ->add('unites', EntityType::class, [
                'label' => 'Unité',
                'class' => Unites::class,
                'choice_label' => 'InZoneDeListe',
                'attr' => [
                    'class' => 'col-sm-12 form-control text-uppercase'
                ],
            ])
            ->add('is_out_cr', CheckboxType::class, [
                'label'=>'Est hors CR?',
                'required'  => false,
            ])            
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Personnels::class,
        ]);
    }
}

src/Controller/PersonnelsController.php
<?php

namespace App\Controller;

use App\Entity\Personnels;
use App\Form\PersonnelsType;
use App\Repository\PersonnelsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;

/**
 * @Route("/personnels")
 */
class PersonnelsController extends AbstractController
{
    /**
     * @Route("/", name="app_personnels_index", methods={"GET"})
     */
    public function index(PersonnelsRepository $personnelsRepository): Response
    {
        return $this->render('personnels/index.html.twig', [
            // 'personnels' => $personnelsRepository->findAll(),
            'personnels' => $personnelsRepository->findBy([], ['id'=>'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="app_personnels_new", methods={"GET", "POST"})
     */
    public function new(Request $request, PersonnelsRepository $personnelsRepository): Response
    {
        $personnel = new Personnels();
        $form = $this->createForm(PersonnelsType::class, $personnel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $personnel->setPersCreated(new DateTime());
            $personnel->setPersUpdated(NULL);
            $personnel->setUser($this->getUser());

            $personnelsRepository->add($personnel, true);

            $this->addFlash('success', 'L\'ajout de personnel effectué avec succès.');

            return $this->redirectToRoute('app_personnels_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personnels/new.html.twig', [
            'personnel' => $personnel,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_personnels_show", methods={"GET"})
     */
    public function show(Personnels $personnel): Response
    {
        return $this->render('personnels/show.html.twig', [
            'personnel' => $personnel,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_personnels_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Personnels $personnel, PersonnelsRepository $personnelsRepository): Response
    {
        $form = $this->createForm(PersonnelsType::class, $personnel);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $personnel->setPersUpdated(new DateTime());
            $personnel->setUser($this->getUser());

            $personnelsRepository->add($personnel, true);

            $this->addFlash('success', 'La modification des renseignements du personnel est effectué avec succès.');

            return $this->redirectToRoute('app_personnels_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('personnels/edit.html.twig', [
            'personnel' => $personnel,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_personnels_delete", methods={"POST"})
     */
    public function delete(Request $request, Personnels $personnel, PersonnelsRepository $personnelsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$personnel->getId(), $request->request->get('_token'))) {
            $personnelsRepository->remove($personnel, true);
        }

        $this->addFlash('success', 'La suppression du personnel est effectué avec succès.');

        return $this->redirectToRoute('app_personnels_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/personnels/_delete_form.html.twig
<form method="post" action="{{ path('app_personnels_delete', {'id': personnel.id}) }}" onsubmit="return confirm('Est-vous sûr de vouloir supprimer cet enregistrement?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ personnel.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Supprimer</button>
</form>

templates/personnels/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/personnels/edit.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Modifier personnel{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-edit"></i>
            Modifier personnel
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_personnels_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
        {{ include('personnels/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_personnels_index') }}">Retour à la liste</a></div>
                <div class="col col-4">{{ include('personnels/_delete_form.html.twig') }}</div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/personnels/index.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Liste des personnels{% endblock %}

{% block body %}
<div class="card">
    <!-- Card-header -->
    <div class="card-header bg-primary">
        <h3 class="card-title">
            {# <a href="{{ path('app_personnels_index') }}" class="btn btn-sm btn-primary"> #}
                <i class="nav-icon fa fa-list"></i>
                Liste des personnels
            {# </a> #}
        </h3>
        <div class="card-tools">
            {# <a href="{{ path('app_motifs_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-print"></i>
            </a> #}
            <a href="{{ path('app_personnels_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row mb-2">
            {% for message in app.flashes('success') %}
            <div class="col col-12 alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="col col-12">
                <table id="example1" class="table table-sm table-bordered table-striped">
                <thead>
                    <tr class="text-center">
                        <th>N°</th>
                        <th>Matricule</th>
                        <th>Grade</th>
                        <th>Nom et prénoms</th>
                        <th>Fonctions</th>
                        <th>Unité</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for personnel in personnels %}
                {% set i = ( i | default(0) ) + 1 %}
                    <tr class="responsive">
                        <td class="text-center">{{ i }}</td>
                        <td>{{ personnel.matriculePers }}</td>
                        <td>{{ personnel.gradePers }}</td>
                        <td>{{ personnel.nomPers }} {{ personnel.prenomsPers ? personnel.prenomsPers : '' }}</td>
                        <td>{{ personnel.fonctionsPers }}</td>
                        {#<td>{{ personnel.isOutCr ? 'Oui' : 'Non' }}</td>#}
                        <td>{{ personnel.unites.InZoneDeListe }}</td>
                        <td class="text-center">
                            <a href="{{ path('app_personnels_show', {'id': personnel.id}) }}" class="btn btn-sm btn-secondary">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ path('app_personnels_edit', {'id': personnel.id}) }}" class="btn btn-sm btn-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="{{ path('app_personnels_delete', {'id': personnel.id}) }}" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr class="bg-warning">
                        <td class="text-center" colspan="7">Pas de personnel enregistré</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-right" colspan="7">
                        <a href="{{ path('app_personnels_new') }}" class="btn btn-sm btn-primary">
                            <i class="fa fa-plus"></i> Créer personnel
                        </a>
                    </th>
                </tr>
                </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {# Ajouté par le developpeur #}
    <!-- Bootstrap 4 -->
    <script src="../../adminlte3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="../../adminlte3.1.0/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/jszip/jszip.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    {# <script src="../../adminlte3.1.0/dist/js/demo.js"></script> #}
    <!-- Page specific script -->
    <script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "lengthChange": false,
            "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
    </script>
{% endblock %}
{# Fin ajout #}

templates/personnels/new.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Créer personnel{% endblock %}

{% block body %}

<div class="card">
    <div class="card-header bg-primary">
            <h3 class="card-title">
                <i class="nav-icon fa fa-plus"></i>
                Créer personnel
            </h3>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
            {{ include('personnels/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_personnels_index') }}">Retour à la liste</a></div>
                <div class="col col-4"></div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/personnels/show.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Personnel{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-eye"></i>
                Personnel
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_personnels_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <tbody>
            <tr>
                <th>Matricule</th>
                <td>{{ personnel.matriculePers }}</td>
            </tr>
            <tr>
                <th>Grade</th>
                <td>{{ personnel.gradePers }}</td>
            </tr>
            <tr>
                <th>Nom et prénoms du personnel </th>
                <td>{{ personnel.nomPers }} {{ personnel.prenomsPers ? personnel.prenomsPers : '' }}</td>
            </tr>
            <tr>
                <th>Unité</th>
                <td>{{ personnel.unites.InZoneDeListe }}</td>
            </tr>            
            <tr>
                <th>Fonction</th>
                <td>{{ personnel.fonctionsPers }}</td>
            </tr>
            
            <tr>
                <th>Est hors CR</th>
                <td>{{ personnel.isOutCr ? 'Oui' : 'Non' }}</td>
            </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <div class="row text-center">
            <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_personnels_index') }}">Retour à la liste</a></div>
            <div class="col col-4">{{ include('personnels/_delete_form.html.twig') }}</div>
            <div class="col col-4"><a class="btn btn-sm btn-warning" href="{{ path('app_personnels_edit', {'id': personnel.id}) }}"><i class="fas fa-edit"></i>  Modifier</a></div>
        </div>
    </div>
</div>
{% endblock %}