src/Entity/Munitions.php
<?php

namespace App\Entity;

use App\Repository\MunitionsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=MunitionsRepository::class)
 * @UniqueEntity(fields="nom_mun", message="La munition entrée est déjà existante")
 */
class Munitions
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=124, unique=true)
     */
    private $nom_mun;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $lot_mun;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $calibre_mun;

    /**
     * @ORM\Column(type="datetime")
     */
    private $mun_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $mun_updated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="munitions")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Designations::class, mappedBy="munitions")
     */
    private $designations;

    public function __construct()
    {
        $this->designations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomMun(): ?string
    {
        return $this->nom_mun;
    }

    public function setNomMun(string $nom_mun): self
    {
        $this->nom_mun = $nom_mun;

        return $this;
    }

    public function getLotMun(): ?string
    {
        return $this->lot_mun;
    }

    public function setLotMun(?string $lot_mun): self
    {
        $this->lot_mun = $lot_mun;

        return $this;
    }

    public function getCalibreMun(): ?float
    {
        return $this->calibre_mun;
    }

    public function setCalibreMun(?float $calibre_mun): self
    {
        $this->calibre_mun = $calibre_mun;

        return $this;
    }

    public function getMunCreated(): ?\DateTimeInterface
    {
        return $this->mun_created;
    }

    public function setMunCreated(\DateTimeInterface $mun_created): self
    {
        $this->mun_created = $mun_created;

        return $this;
    }

    public function getMunUpdated(): ?\DateTimeInterface
    {
        return $this->mun_updated;
    }

    public function setMunUpdated(?\DateTimeInterface $mun_updated): self
    {
        $this->mun_updated = $mun_updated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Designations>
     */
    public function getDesignations(): Collection
    {
        return $this->designations;
    }

    public function addDesignation(Designations $designation): self
    {
        if (!$this->designations->contains($designation)) {
            $this->designations[] = $designation;
            $designation->setMunitions($this);
        }

        return $this;
    }

    public function removeDesignation(Designations $designation): self
    {
        if ($this->designations->removeElement($designation)) {
            // set the owning side to null (unless already changed)
            if ($designation->getMunitions() === $this) {
                $designation->setMunitions(null);
            }
        }

        return $this;
    }
}

src/Form/MunitionsType.php
<?php

namespace App\Form;

use App\Entity\Munitions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MunitionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_mun', TextType::class, [
                'label' => 'Dénomination',
                'required' => true,
            ])
            ->add('lot_mun', TextType::class, [
                'label' => 'Lot',
                'required' => false,
            ])
            ->add('calibre_mun', NumberType::class, [
                'label' => 'Calibre',
                'required' => true,
                'invalid_message' => 'Veuillez entrer un nombre décimal.'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Munitions::class,
        ]);
    }
}

src/Controller/MunitionsController.php
<?php

namespace App\Controller;

use App\Entity\Munitions;
use App\Form\MunitionsType;
use App\Repository\MunitionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;

/**
 * @Route("/munitions")
 */
class MunitionsController extends AbstractController
{
    /**
     * @Route("/", name="app_munitions_index", methods={"GET"})
     */
    public function index(MunitionsRepository $munitionsRepository): Response
    {
        return $this->render('munitions/index.html.twig', [
            // 'munitions' => $munitionsRepository->findAll(),
            'munitions' => $munitionsRepository->findBy([], ['id'=>'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="app_munitions_new", methods={"GET", "POST"})
     */
    public function new(Request $request, MunitionsRepository $munitionsRepository): Response
    {
        $munition = new Munitions();
        $form = $this->createForm(MunitionsType::class, $munition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $munition->setMunCreated(new DateTime());
            $munition->setMunUpdated(NULL);
            $munition->setUser($this->getUser());

            $this->addFlash('success', 'L\'ajout de munition de la munition est effectuée avec succès');

            $munitionsRepository->add($munition, true);

            return $this->redirectToRoute('app_munitions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('munitions/new.html.twig', [
            'munition' => $munition,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_munitions_show", methods={"GET"})
     */
    public function show(Munitions $munition): Response
    {
        return $this->render('munitions/show.html.twig', [
            'munition' => $munition,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_munitions_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Munitions $munition, MunitionsRepository $munitionsRepository): Response
    {
        $form = $this->createForm(MunitionsType::class, $munition);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $munition->setMunUpdated(new DateTime());
            $munition->setUser($this->getUser());

            $this->addFlash('success', 'La modification de la munition est effectuée avec succès');

            $munitionsRepository->add($munition, true);

            return $this->redirectToRoute('app_munitions_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('munitions/edit.html.twig', [
            'munition' => $munition,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_munitions_delete", methods={"POST"})
     */
    public function delete(Request $request, Munitions $munition, MunitionsRepository $munitionsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$munition->getId(), $request->request->get('_token'))) {
            $munitionsRepository->remove($munition, true);

            $this->addFlash('success', 'La suppression de la munition est effectuée avec succès');
        }

        return $this->redirectToRoute('app_munitions_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/munitions/_delete_form.html.twig
<form method="post" action="{{ path('app_munitions_delete', {'id': munition.id}) }}" onsubmit="return confirm('Est-vous sûr de vouloir supprimer cet enregistrement?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ munition.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Supprimer</button>
</form>

templates/munitions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/munitions/edit.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Edit Munitions{% endblock %}

{% block body %}
    <h1>Edit Munitions</h1>

    {{ include('munitions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_munitions_index') }}">back to list</a>

    {{ include('munitions/_delete_form.html.twig') }}
{% endblock %}
 #}
{% extends 'base_with_menu.html.twig' %}

{% block title %}Modifier munition{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-edit"></i>
            Modifier munition
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_munitions_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
        {{ include('munitions/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_munitions_index') }}">Retour à la liste</a></div>
                <div class="col col-4">{{ include('munitions/_delete_form.html.twig') }}</div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/munitions/index.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Liste des munitions{% endblock %}

{% block body %}
<div class="card">
    <!-- Card-header -->
    <div class="card-header bg-primary">
        <h3 class="card-title">
            {# <a href="{{ path('app_munitions_index') }}" class="btn btn-sm btn-primary"> #}
                <i class="nav-icon fa fa-list"></i> Liste des munitions
            {# </a> #}
        </h3>
        <div class="card-tools">
            {# <a href="{{ path('app_motifs_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-print"></i>
            </a> #}
            <a href="{{ path('app_munitions_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row mb-2">
            {% for message in app.flashes('success') %}
            <div class="col col-12 alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="col col-12">
                <table id="example1" class="table table-sm table-bordered table-striped">
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>Nom munition</th>
                        <th>Lot munition</th>
                        <th>Calibre munition</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for munition in munitions %}
                {% set i = ( i | default(0) ) + 1 %}
                    <tr>
                        <td class="text-center">{{ i }}</td>
                        <td>{{ munition.nomMun }}</td>
                        <td>{{ munition.lotMun }}</td>
                        <td>{{ munition.calibreMun }}</td>
                        <td class="text-center">
                            <a href="{{ path('app_munitions_show', {'id': munition.id}) }}" class="btn btn-sm btn-secondary">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ path('app_munitions_edit', {'id': munition.id}) }}" class="btn btn-sm btn-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="{{ path('app_munitions_delete', {'id': munition.id}) }}" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr class="bg-warning">
                        <td class="text-center" colspan="5">Pas de munition enregistrée</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-right" colspan="5">
                        <a href="{{ path('app_munitions_new') }}" class="btn btn-sm btn-primary">
                            <i class="fa fa-plus"></i> Créer munition
                        </a>
                    </th>
                </tr>
                </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {# Ajouté par le developpeur #}
    <!-- Bootstrap 4 -->
    <script src="../../adminlte3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="../../adminlte3.1.0/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/jszip/jszip.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    {# <script src="../../adminlte3.1.0/dist/js/demo.js"></script> #}
    <!-- Page specific script -->
    <script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "lengthChange": false,
            "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
    </script>
{% endblock %}
{# Fin ajout #}

templates/munitions/new.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Créer munition{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-plus"></i>
            Créer munition
        </h3>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
            {{ include('munitions/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_munitions_index') }}">Retour à la liste</a></div>
                <div class="col col-4"></div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/munitions/show.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Munition{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-eye"></i>
                Munition
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_munitions_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <tbody>
                <tr>
                    <th>Dénomination</th>
                    <td>{{ munition.nomMun }}</td>
                </tr>
                <tr>
                    <th>Lot</th>
                    <td>{{ munition.lotMun }}</td>
                </tr>
                <tr>
                    <th>Calibre</th>
                    <td>{{ munition.calibreMun }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <div class="row text-center">
            <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_munitions_index') }}">Retour à la liste</a></div>
            <div class="col col-4">{{ include('munitions/_delete_form.html.twig') }}</div>
            <div class="col col-4"><a class="btn btn-sm btn-warning" href="{{ path('app_munitions_edit', {'id': munition.id}) }}"><i class="fas fa-edit"></i>  Modifier</a></div>
        </div>
    </div>
</div>
{% endblock %}