src/Entity/TypeArmements.php
<?php

namespace App\Entity;

use App\Repository\TypeArmementsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=TypeArmementsRepository::class)
 * @UniqueEntity(fields="nom_arm", message="Le type d'armement entré est déjà existant")
 */
class TypeArmements
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=124, unique=true)
     */
    private $nom_arm;

    /**
     * @ORM\Column(type="string", length=64, nullable=true)
     */
    private $abreviation_arm;

    /**
     * @ORM\Column(type="datetime")
     */
    private $arm_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $arm_updated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="typeArmements")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Designations::class, mappedBy="type_armements")
     */
    private $designations;

    public function __construct()
    {
        $this->designations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomArm(): ?string
    {
        return $this->nom_arm;
    }

    public function setNomArm(string $nom_arm): self
    {
        $this->nom_arm = $nom_arm;

        return $this;
    }

    public function getAbreviationArm(): ?string
    {
        return $this->abreviation_arm;
    }

    public function setAbreviationArm(?string $abreviation_arm): self
    {
        $this->abreviation_arm = $abreviation_arm;

        return $this;
    }

    public function getArmCreated(): ?\DateTimeInterface
    {
        return $this->arm_created;
    }

    public function setArmCreated(\DateTimeInterface $arm_created): self
    {
        $this->arm_created = $arm_created;

        return $this;
    }

    public function getArmUpdated(): ?\DateTimeInterface
    {
        return $this->arm_updated;
    }

    public function setArmUpdated(?\DateTimeInterface $arm_updated): self
    {
        $this->arm_updated = $arm_updated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Designations>
     */
    public function getDesignations(): Collection
    {
        return $this->designations;
    }

    public function addDesignation(Designations $designation): self
    {
        if (!$this->designations->contains($designation)) {
            $this->designations[] = $designation;
            $designation->setTypeArmements($this);
        }

        return $this;
    }

    public function removeDesignation(Designations $designation): self
    {
        if ($this->designations->removeElement($designation)) {
            // set the owning side to null (unless already changed)
            if ($designation->getTypeArmements() === $this) {
                $designation->setTypeArmements(null);
            }
        }

        return $this;
    }
}

src/Form/TypeArmementsType.php
<?php

namespace App\Form;

use App\Entity\TypeArmements;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;

class TypeArmementsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_arm', TextType::class, [
                'label' => 'Type armement',
                'required' => true
            ])
            ->add('abreviation_arm', TextType::class, [
                'label' => 'Abréviation',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => TypeArmements::class,
        ]);
    }
}

src/Controller/TypeArmementsController.php
<?php

namespace App\Controller;

use App\Entity\TypeArmements;
use App\Form\TypeArmementsType;
use App\Repository\TypeArmementsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use DateTime;

/**
 * @Route("/type_armements")
 */
class TypeArmementsController extends AbstractController
{
    /**
     * @Route("/", name="app_type_armements_index", methods={"GET"})
     */
    public function index(TypeArmementsRepository $typeArmementsRepository): Response
    {
        return $this->render('type_armements/index.html.twig', [
            // 'type_armements' => $typeArmementsRepository->findAll(),
            'type_armements' => $typeArmementsRepository->findBy([], ['id'=>'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="app_type_armements_new", methods={"GET", "POST"})
     */
    public function new(Request $request, TypeArmementsRepository $typeArmementsRepository): Response
    {
        $typeArmement = new TypeArmements();
        $form = $this->createForm(TypeArmementsType::class, $typeArmement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $typeArmement->setArmCreated(new DateTime());
            $typeArmement->setArmUpdated(NULL);
            $typeArmement->setUser($this->getUser());

            $typeArmementsRepository->add($typeArmement, true);

            $this->addFlash('success', 'L\'ajout de type d\'armement est effectué avec succès.');

            return $this->redirectToRoute('app_type_armements_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type_armements/new.html.twig', [
            'type_armement' => $typeArmement,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_type_armements_show", methods={"GET"})
     */
    public function show(TypeArmements $typeArmement): Response
    {
        return $this->render('type_armements/show.html.twig', [
            'type_armement' => $typeArmement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_type_armements_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, TypeArmements $typeArmement, TypeArmementsRepository $typeArmementsRepository): Response
    {
        $form = $this->createForm(TypeArmementsType::class, $typeArmement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $typeArmement->setArmUpdated(new DateTime());
            $typeArmement->setUser($this->getUser());

            $this->addFlash('success', 'La modification de type d\'armement est effectué avec succès');

            $typeArmementsRepository->add($typeArmement, true);

            return $this->redirectToRoute('app_type_armements_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('type_armements/edit.html.twig', [
            'type_armement' => $typeArmement,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_type_armements_delete", methods={"POST"})
     */
    public function delete(Request $request, TypeArmements $typeArmement, TypeArmementsRepository $typeArmementsRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$typeArmement->getId(), $request->request->get('_token'))) {
            $typeArmementsRepository->remove($typeArmement, true);

            $this->addFlash('success', 'La suppression de type d\'armement effetué avec succès');
        }

        return $this->redirectToRoute('app_type_armements_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/type_armements/_delete_form.html.twig
<form method="post" action="{{ path('app_type_armements_delete', {'id': type_armement.id}) }}" onsubmit="return confirm('Est-vous sûr de vouloir supprimer cet enregistrement?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ type_armement.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Supprimer</button>
</form>

templates/type_armements/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/type_armements/edit.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Edit TypeArmements{% endblock %}

{% block body %}
    <h1>Edit TypeArmements</h1>

    {{ include('type_armements/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_type_armements_index') }}">back to list</a>

    {{ include('type_armements/_delete_form.html.twig') }}
{% endblock %} #}

{% extends 'base_with_menu.html.twig' %}

{% block title %}Modifier type d'armement{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-edit"></i>
            Modifier type d'armement
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_type_armements_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
        {{ include('type_armements/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_type_armements_index') }}">Retour à la liste</a></div>
                <div class="col col-4">{{ include('type_armements/_delete_form.html.twig') }}</div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/type_armements/index.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}TypeArmements index{% endblock %}

{% block body %}
    <h1>TypeArmements index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Nom_arm</th>
                <th>Abreviation_arm</th>
                <th>Arm_created</th>
                <th>Arm_updated</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for type_armement in type_armements %}
            <tr>
                <td>{{ type_armement.id }}</td>
                <td>{{ type_armement.nomArm }}</td>
                <td>{{ type_armement.abreviationArm }}</td>
                <td>{{ type_armement.armCreated ? type_armement.armCreated|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ type_armement.armUpdated ? type_armement.armUpdated|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_type_armements_show', {'id': type_armement.id}) }}">show</a>
                    <a href="{{ path('app_type_armements_edit', {'id': type_armement.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_type_armements_new') }}">Create new</a>
{% endblock %} #}
{% extends 'base_with_menu.html.twig' %}

{% block title %}Liste des types armements{% endblock %}

{% block body %}
<div class="card">
    <!-- Card-header -->
    <div class="card-header bg-primary">
        <h3 class="card-title">
            {# <a href="{{ path('app_type_armements_index') }}" class="btn btn-sm btn-primary"> #}
                <i class="nav-icon fa fa-list"></i>
                Liste des types armements
            {# </a> #}
        </h3>
        <div class="card-tools">
            {# <a href="{{ path('app_motifs_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-print"></i>
            </a> #}
            <a href="{{ path('app_type_armements_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row mb-2">
            {% for message in app.flashes('success') %}
            <div class="col col-12 alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="col col-12">
                <table id="example1" class="table table-sm table-bordered table-striped">
                <thead>
                    <tr>
                        <th>N°</th>
                        <th>Type armement</th>
                        <th>Abréviation type armement</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for type_armement in type_armements %}
                {% set i = ( i | default(0) ) + 1 %}
                    <tr>
                        <td class="text-center">{{ i }}</td>
                        <td>{{ type_armement.nomArm }}</td>
                        <td>{{ type_armement.abreviationArm }}</td>
                        <td class="text-center">
                            <a href="{{ path('app_type_armements_show', {'id': type_armement.id}) }}" class="btn btn-sm btn-secondary">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ path('app_type_armements_edit', {'id': type_armement.id}) }}" class="btn btn-sm btn-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="{{ path('app_type_armements_delete', {'id': type_armement.id}) }}" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr class="bg-warning">
                        <td class="text-center" colspan="4">Pas de type d'armement enregistré</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-right" colspan="5">
                        <a href="{{ path('app_type_armements_new') }}" class="btn btn-sm btn-primary">
                            <i class="fa fa-plus"></i> Créer type armement
                        </a>
                    </th>
                </tr>
                </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {# Ajouté par le developpeur #}
    <!-- Bootstrap 4 -->
    <script src="../../adminlte3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="../../adminlte3.1.0/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/jszip/jszip.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    {# <script src="../../adminlte3.1.0/dist/js/demo.js"></script> #}
    <!-- Page specific script -->
    <script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "lengthChange": false,
            "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
    </script>
{% endblock %}
{# Fin ajout #}

templates/type_armements/new.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}New TypeArmements{% endblock %}

{% block body %}
    <h1>Create new TypeArmements</h1>

    {{ include('type_armements/_form.html.twig') }}

    <a href="{{ path('app_type_armements_index') }}">back to list</a>
{% endblock %} #}
{% extends 'base_with_menu.html.twig' %}

{% block title %}Créer type d'armement{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
            <h3 class="card-title">
                <i class="nav-icon fa fa-plus"></i>
                Créer type d'armement
            </h3>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
            {{ include('type_armements/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_type_armements_index') }}">Retour à la liste</a></div>
                <div class="col col-4"></div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/type_armements/show.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}TypeArmements{% endblock %}

{% block body %}
    <h1>TypeArmements</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ type_armement.id }}</td>
            </tr>
            <tr>
                <th>Nom_arm</th>
                <td>{{ type_armement.nomArm }}</td>
            </tr>
            <tr>
                <th>Abreviation_arm</th>
                <td>{{ type_armement.abreviationArm }}</td>
            </tr>
            <tr>
                <th>Arm_created</th>
                <td>{{ type_armement.armCreated ? type_armement.armCreated|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Arm_updated</th>
                <td>{{ type_armement.armUpdated ? type_armement.armUpdated|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_type_armements_index') }}">back to list</a>

    <a href="{{ path('app_type_armements_edit', {'id': type_armement.id}) }}">edit</a>

    {{ include('type_armements/_delete_form.html.twig') }}
{% endblock %} #}
{% extends 'base_with_menu.html.twig' %}

{% block title %}Type de service{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-eye"></i>
            Type de service
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_type_armements_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <tbody>
                <tr>
                    <th>Type d'armement</th>
                    <td>{{ type_armement.nomArm }}</td>
                </tr>
                <tr>
                    <th>Abréviation</th>
                    <td>{{ type_armement.abreviationArm }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <div class="row text-center">
            <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_type_armements_index') }}">Retour à la liste</a></div>
            <div class="col col-4">{{ include('type_armements/_delete_form.html.twig') }}</div>
            <div class="col col-4"><a class="btn btn-sm btn-warning" href="{{ path('app_type_armements_edit', {'id': type_armement.id}) }}"><i class="fas fa-edit"></i>  Modifier</a></div>
        </div>
    </div>
</div>
{% endblock %}