src/Entity/Absences.php
<?php

namespace App\Entity;

use App\Repository\AbsencesRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=AbsencesRepository::class)
 * @UniqueEntity(
 *  fields={"personnels", "motifs", "date_debut_abs", "date_fin_abs"},
 *  errorPath="personnels",
 *  message="L'absence du personnel avec ce motif dans cette période est déjà existante"
 * )
 */
class Absences
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_debut_abs;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_fin_abs;

    /**
     * @ORM\Column(type="datetime")
     */
    private $abs_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $abs_updated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="absences")
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity=Motifs::class, inversedBy="absences")
     */
    private $motifs;

    /**
     * @ORM\ManyToOne(targetEntity=Personnels::class, inversedBy="absences")
     */
    private $personnels;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateDebutAbs(): ?\DateTimeInterface
    {
        return $this->date_debut_abs;
    }

    public function setDateDebutAbs(\DateTimeInterface $date_debut_abs): self
    {
        $this->date_debut_abs = $date_debut_abs;

        return $this;
    }

    public function getDateFinAbs(): ?\DateTimeInterface
    {
        return $this->date_fin_abs;
    }

    public function setDateFinAbs(\DateTimeInterface $date_fin_abs): self
    {
        $this->date_fin_abs = $date_fin_abs;

        return $this;
    }

    public function getAbsCreated(): ?\DateTimeInterface
    {
        return $this->abs_created;
    }

    public function setAbsCreated(\DateTimeInterface $abs_created): self
    {
        $this->abs_created = $abs_created;

        return $this;
    }

    public function getAbsUpdated(): ?\DateTimeInterface
    {
        return $this->abs_updated;
    }

    public function setAbsUpdated(?\DateTimeInterface $abs_updated): self
    {
        $this->abs_updated = $abs_updated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getMotifs(): ?Motifs
    {
        return $this->motifs;
    }

    public function setMotifs(?Motifs $motifs): self
    {
        $this->motifs = $motifs;

        return $this;
    }

    public function getPersonnels(): ?Personnels
    {
        return $this->personnels;
    }

    public function setPersonnels(?Personnels $personnels): self
    {
        $this->personnels = $personnels;

        return $this;
    }

}

src/Entity/Motifs.php
<?php

namespace App\Entity;

use App\Repository\MotifsRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MotifsRepository::class)
 */
class Motifs
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $libelle_mtf;

    /**
     * @ORM\Column(type="string", length=124, nullable=true)
     */
    private $abreviation_mtf;

    /**
     * @ORM\Column(type="datetime")
     */
    private $mtf_created;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $mtf_updated;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="motifs")
     */
    private $user;

    /**
     * @ORM\OneToMany(targetEntity=Absences::class, mappedBy="motifs")
     */
    private $absences;

    public function __construct()
    {
        $this->absences = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelleMtf(): ?string
    {
        return $this->libelle_mtf;
    }

    public function setLibelleMtf(string $libelle_mtf): self
    {
        $this->libelle_mtf = $libelle_mtf;

        return $this;
    }

    public function getAbreviationMtf(): ?string
    {
        return $this->abreviation_mtf;
    }

    public function setAbreviationMtf(?string $abreviation_mtf): self
    {
        $this->abreviation_mtf = $abreviation_mtf;

        return $this;
    }

    public function getMtfCreated(): ?\DateTimeInterface
    {
        return $this->mtf_created;
    }

    public function setMtfCreated(\DateTimeInterface $mtf_created): self
    {
        $this->mtf_created = $mtf_created;

        return $this;
    }

    public function getMtfUpdated(): ?\DateTimeInterface
    {
        return $this->mtf_updated;
    }

    public function setMtfUpdated(\DateTimeInterface $mtf_updated): self
    {
        $this->mtf_updated = $mtf_updated;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, Absences>
     */
    public function getAbsences(): Collection
    {
        return $this->absences;
    }

    public function addAbsence(Absences $absence): self
    {
        if (!$this->absences->contains($absence)) {
            $this->absences[] = $absence;
            $absence->setMotifs($this);
        }

        return $this;
    }

    public function removeAbsence(Absences $absence): self
    {
        if ($this->absences->removeElement($absence)) {
            // set the owning side to null (unless already changed)
            if ($absence->getMotifs() === $this) {
                $absence->setMotifs(null);
            }
        }

        return $this;
    }
}

src/Form/AbsencesType.php
<?php

namespace App\Form;

use App\Entity\Absences;
use App\Entity\Motifs;
use App\Entity\Personnels;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class AbsencesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('personnels', EntityType::class, [
                'label' => 'Choisir le personnel',
                'class' => Personnels::class,
                'attr' => [
                    'class' => 'col-sm-12 form-control select'
                ],
                'query_builder' => function (EntityRepository $_er){
                        return $_er
                            ->createQueryBuilder('c')
                            ->where("c.is_out_cr = 0");
                },
                'choice_label' => 'InZoneDeListe',
                'required' => false,
            ])
            ->add('motifs', EntityType::class, [
                'label' => 'Choisir le motif d\'absence',
                'class' => Motifs::class,
                'choice_label' => 'libelleMtf',
                'attr' => [
                    'class' => 'col-sm-12 form-control select'
                ],
                'required' => false,
            ])
            ->add('date_debut_abs', null, [
                'label' => 'Début d\'absence',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datetimepicker',
                ],
                'required' => true,
            ])
            ->add('date_fin_abs', null, [
                'label' => 'Fin d\'absence',
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'datetimepicker',
                ],
                'required' => true,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Absences::class,
        ]);
    }
}

src/Controller/AbsencesController.php
<?php

namespace App\Controller;

use App\Entity\Absences;
use App\Form\AbsencesType;
use App\Repository\AbsencesRepository;
use DateTime;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/absences")
 */
class AbsencesController extends AbstractController
{
    /**
     * @Route("/", name="app_absences_index", methods={"GET"})
     */
    public function index(AbsencesRepository $absencesRepository): Response
    {
        return $this->render('absences/index.html.twig', [
            // 'absences' => $absencesRepository->findAll(),
            'absences' => $absencesRepository->findBy([],['id'=>'DESC']),
        ]);
    }

    /**
     * @Route("/new", name="app_absences_new", methods={"GET", "POST"})
     */
    public function new(Request $request, AbsencesRepository $absencesRepository): Response
    {
        $absence = new Absences();
        $form = $this->createForm(AbsencesType::class, $absence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $absence->setAbsCreated(new DateTime());
            $absence->setAbsUpdated(NULL);
            $absence->setUser($this->getUser());

            $absencesRepository->add($absence, true);

            $this->addFlash('success', 'L\'ajout de l\'absence du personnel est effectué avec succès.');

            return $this->redirectToRoute('app_absences_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('absences/new.html.twig', [
            'absence' => $absence,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_absences_show", methods={"GET"})
     */
    public function show(Absences $absence): Response
    {
        return $this->render('absences/show.html.twig', [
            'absence' => $absence,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_absences_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Absences $absence, AbsencesRepository $absencesRepository): Response
    {
        $form = $this->createForm(AbsencesType::class, $absence);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {

            $absence->setAbsUpdated(new DateTime());
            $absence->setUser($this->getUser());

            $absencesRepository->add($absence, true);

            $this->addFlash('success', 'La modification de l\'absence est effectuée avec succès.');

            return $this->redirectToRoute('app_absences_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('absences/edit.html.twig', [
            'absence' => $absence,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_absences_delete", methods={"POST"})
     */
    public function delete(Request $request, Absences $absence, AbsencesRepository $absencesRepository): Response
    {
        if ($this->isCsrfTokenValid('delete'.$absence->getId(), $request->request->get('_token'))) {
            $absencesRepository->remove($absence, true);

            $this->addFlash('success', 'La suppression de l\'absence est effectuée avec succès.');
        }

        return $this->redirectToRoute('app_absences_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/absences/_delete_form.html.twig
<form method="post" action="{{ path('app_absences_delete', {'id': absence.id}) }}" onsubmit="return confirm('Est-vous sûr de vouloir supprimer cet enregistrement?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ absence.id) }}">
    <button class="btn btn-sm btn-danger"><i class="fa fa-trash"></i> Supprimer</button>
</form>

templates/absences/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-sm btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/absences/edit.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Modifier absence{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-edit"></i>
            Modifier absence
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_absences_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    {% for message in app.flashes('success') %}
    <div class="alert alert-success">
            {{ message }}
    </div>
    {% endfor %}
    <div class="card-body">
        {{ include('absences/_form.html.twig', {'button_label': 'Enregistrer'}) }}
    </div>
    <div class="card-footer">
        <div class="row text-center">
                <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_absences_index') }}">Retour à la liste</a></div>
                <div class="col col-4">{{ include('absences/_delete_form.html.twig') }}</div>
                <div class="col col-4"></div>
        </div>
    </div>
</div>
{% endblock %}

templates/absences/index.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Liste des absences{% endblock %}

{% block body %}
<div class="card">
    <!-- Card-header -->
    <div class="card-header bg-primary">
        <h3 class="card-title">
            {# <a href="{{ path('app_absences_index') }}" class="btn btn-sm btn-primary"> #}
                <i class="nav-icon fa fa-list"></i>
                Liste des absences
            {# </a> #}
        </h3>
        <div class="card-tools">
            {# <a href="{{ path('app_absences_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-print"></i>
            </a> #}
            <a href="{{ path('app_absences_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <!-- /.card-header -->
    <div class="card-body">
        <div class="row mb-2">
            {% for message in app.flashes('success') %}
            <div class="col col-12 alert alert-success">
                {{ message }}
            </div>
            {% endfor %}
            <div class="col col-12">
                <table id="example1" class="table table-sm table-bordered table-striped">
                <thead>
                    <tr class="text-center">
                        <th>N°</th>
                        <th>Matricule personnel</th>
                        <th>Motif d'absence</th>
                        <th>Début de l'absence</th>
                        <th>Fin de l'absence</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                {% for absence in absences %}
                {% set i = ( i | default(0) ) + 1 %}
                    <tr class="text-center">
                        <td>{{ i }}</td>
                        <td>{{ absence.personnels ? absence.personnels.InZoneDeListe : '' }}</td>
                        <td>{{ absence.motifs ? absence.motifs.abreviationMtf : '' }}</td>
                        <td>{{ absence.dateDebutAbs ? absence.dateDebutAbs|date('d/m/Y H:i:s') : '' }}</td>
                        <td>{{ absence.dateFinAbs ? absence.dateFinAbs|date('d/m/Y H:i:s') : '' }}</td>
                        <td class="text-center">
                            <a href="{{ path('app_absences_show', {'id': absence.id}) }}" class="btn btn-sm btn-secondary">
                                <i class="fas fa-eye"></i>
                            </a>
                            <a href="{{ path('app_absences_edit', {'id': absence.id}) }}" class="btn btn-sm btn-warning">
                                <i class="fas fa-edit"></i>
                            </a>
                            <a href="{{ path('app_absences_delete', {'id': absence.id}) }}" class="btn btn-sm btn-danger">
                                <i class="fas fa-trash"></i>
                            </a>
                        </td>
                    </tr>
                {% else %}
                    <tr class="bg-warning">
                        <td class="text-center" colspan="6">Pas d'absence enregistré</td>
                    </tr>
                {% endfor %}
                </tbody>
                <tfoot>
                <tr>
                    <th class="text-right" colspan="6">
                        <a href="{{ path('app_absences_new') }}" class="btn btn-sm btn-primary">
                            <i class="fa fa-plus"></i> Créer absence
                        </a>
                    </th>
                </tr>
                </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block javascripts %}
    {# Ajouté par le developpeur #}
    <!-- Bootstrap 4 -->
    <script src="../../adminlte3.1.0/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="../../adminlte3.1.0/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/jszip/jszip.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="../../adminlte3.1.0/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE for demo purposes -->
    {# <script src="../../adminlte3.1.0/dist/js/demo.js"></script> #}
    <!-- Page specific script -->
    <script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true,
            "lengthChange": false,
            "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"],
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
        $('#example2').DataTable({
            "paging": true,
            "lengthChange": false,
            "searching": false,
            "ordering": true,
            "info": true,
            "autoWidth": false,
            "responsive": true,
        });
    });
    </script>
{% endblock %}
{# Fin ajout #}

templates/absences/new.html.twig
{% extends 'base_with_menu.html.twig' %}

{% block title %}Créer absence{% endblock %}

{% block body %}
<div class="card">
        <div class="card-header bg-primary">
                <h3 class="card-title">
                        {# <a href="{{ path('app_absences_index') }}" class="btn btn-sm btn-primary"> #}
                                <i class="nav-icon fa fa-plus"></i>
                                Créer absence
                        {# </a> #}
                </h3>
        </div>
        {% for message in app.flashes('success') %}
        <div class="alert alert-success">
                {{ message }}
        </div>
        {% endfor %}
        <div class="card-body">
                {{ include('absences/_form.html.twig', {'button_label': 'Enregistrer'}) }}
        </div>
        <div class="card-footer">
                <div class="row text-center">
                        <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_absences_index') }}">Retour à la liste</a></div>
                        <div class="col col-4"></div>
                        <div class="col col-4"></div>
                </div>
        </div>
</div>
{% endblock %}

templates/absences/show.html.twig
{# {% extends 'base.html.twig' %}

{% block title %}Absences{% endblock %}

{% block body %}
    <h1>Absences</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ absence.id }}</td>
            </tr>
            <tr>
                <th>Date_debut_abs</th>
                <td>{{ absence.dateDebutAbs ? absence.dateDebutAbs|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_fin_abs</th>
                <td>{{ absence.dateFinAbs ? absence.dateFinAbs|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_absences_index') }}">back to list</a>

    <a href="{{ path('app_absences_edit', {'id': absence.id}) }}">edit</a>

    {{ include('absences/_delete_form.html.twig') }}
{% endblock %} #}
{% extends 'base_with_menu.html.twig' %}

{% block title %}Détail de l'absence{% endblock %}

{% block body %}
<div class="card">
    <div class="card-header bg-primary">
        <h3 class="card-title">
            <i class="nav-icon fa fa-eye"></i>
            Détail de l'absence
        </h3>
        <div class="card-tools">
            <a href="{{ path('app_absences_new') }}" class="btn btn-sm btn-light">
                <i class="fa fa-plus"></i>
            </a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <tbody>
                <tr>
                    <th>Personnel</th>
                    <td>{{ absence.personnels ? absence.personnels.InZoneDeListe : '' }}</td>
                </tr>
                <tr>
                    <th>Motif d'absence</th>
                    <td>{{ absence.motifs ? absence.motifs.abreviationMtf : '' }}</td>
                </tr>
                <tr>
                    <th>Début de l'absence</th>
                    <td>{{ absence.dateDebutAbs ? absence.dateDebutAbs|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
                <tr>
                    <th>Fin de l'absence</th>
                    <td>{{ absence.dateFinAbs ? absence.dateFinAbs|date('d/m/Y H:i:s') : '' }}</td>
                </tr>
            </tbody>
        </table>
    </div>
    <div class="card-footer">
        <div class="row text-center">
            <div class="col col-4"><a class="btn btn-sm btn-default" href="{{ path('app_absences_index') }}">Retour à la liste</a></div>
            <div class="col col-4">{{ include('absences/_delete_form.html.twig') }}</div>
            <div class="col col-4"><a class="btn btn-sm btn-warning" href="{{ path('app_absences_edit', {'id': absence.id}) }}"><i class="fas fa-edit"></i>  Modifier</a></div>
        </div>
    </div>
</div>
{% endblock %}